name: Daily Weather Update
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libfreetype6-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R Packages
        run: |
          Rscript -e '
            install.packages("pak", repos="https://r-lib.github.io/p/pak/stable/")
            pak::pak(c(
              "tidyverse", "rdwd", "geosphere", "shiny",
              "bslib", "plotly", "rsconnect", "leaflet",
              "bsicons", "lubridate",
              "cpp11", "progress"
            ))
            cat("rsconnect path:", find.package("rsconnect"), "\n")
          '

      - name: Run Update Script
        run: Rscript update_weather.R

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git stash
          git pull --rebase origin main
          git stash pop
          git add Bro_web_app/weather_data_full.rds
          git commit -m "Daily weather update: $(date +'%Y-%m-%d')" || exit 0
          git push

      - name: Deploy to shinyapps.io
        env:
          SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
        run: |
          Rscript -e "
            rsconnect::setAccountInfo(
              name=Sys.getenv('SHINY_ACC_NAME'),
              token=Sys.getenv('SHINY_TOKEN'),
              secret=Sys.getenv('SHINY_SECRET')
            )
            rsconnect::deployApp(
              appDir='Bro_web_app',
              appName='orchard_weather_tool',
              forceUpdate=TRUE,
              lint=FALSE
            )
          "
