name: Daily Weather Update
on:
  schedule:
    - cron: '0 4 * * *' # Runs every day at 04:00 UTC
  workflow_dispatch: # Allows manual testing

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          
      - name: Install R Packages
       run: |
         Rscript -e 'install.packages(c("tidyverse", "rdwd", "geosphere", "shiny", "bslib", "plotly", "rsconnect", "leaflet", "bsicons", "lubridate"), lib="/usr/local/lib/R/site-library")'
     
      - name: Run Update Script
        run: Rscript update_weather.R

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add Bro_web_app/weather_data_full.rds
          git commit -m "Daily weather update: $(date +'%Y-%m-%d')" || exit 0
          git pull --rebase origin main
          git push  
          
      - name: Deploy to shinyapps.io
        env:
          SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
          SHINY_TOKEN: ${{ secrets.SHINY_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINY_SECRET }}
        run: |
          Rscript -e "
            library('rsconnect', lib.loc='/usr/local/lib/R/site-library')
            rsconnect::setAccountInfo(
              name=Sys.getenv('SHINY_ACC_NAME'),
              token=Sys.getenv('SHINY_TOKEN'),
              secret=Sys.getenv('SHINY_SECRET')
            )
            rsconnect::deployApp(appDir='Bro_web_app', appName='orchard_weather_tool', forceUpdate=TRUE)
          "
